### ISSUE TITLE
Field package hibái

### ISSUE THREAD

**Issue by tamas-visy** [BME-MIT-IET/iet-hf2021-iglue#12]
# Összefoglalás

Összegyűjti a Field package-ben manuális átnézéssel és statikus analízis eszközök futtatásával talált hibákat - pontosabban ezeknek azt részét, amit ki is tervezünk javítani.
Ez a #2 alá tartozik.

# Dokumentáció

Minden fájlnak, ami tartalmaz valami javítandót, lesz egy kommentje.
A kommentek az alábbi vázat követik:

> ## Fájlnév
> 1. hiba leírása
> 2. hiba leírása
>...

Ha egy hiba ki lett javítva, azt a megfelelő sor ~~áthúzásával~~ jelezzük.
Ha egy fájl minden hibája ki lett javítva, a címet is ~~áthúzzuk~~.

**Comment by tamas-visy** [comment]
## ~~Hole~~
~~1. setItem üres blokkon belül is kommentelni kell, hogy miért üres; egyéb hiányos dokumentáció~~
~~2. Fel nem használt változó~~

**Comment by tamas-visy** [comment]
## ~~IceBlock~~
~~1. Hiányos dokumentáció~~
~~2. Fel nem használt változó~~
~~3. Hibás megvalósítása DecrLayerOfSnow-nak (ha a hómennyiség 0-ra csökken nem nyílik meg elsőre)~~

**Comment by tamas-visy** [comment]
## ~~Field~~
~~1. Hiányos dokumentáció~~
~~2. Fel nem használt változó~~
~~3. DecrLayerOfSnow abstract pedig hasonló az implementációja~~

**Comment by bogarb** [comment]
BDD tesztelés közben felmerült a következő hibajelenség:
Specifikáció szerint, ha egy instabil jégtábla átfordul, akkor a rajta lévő hóréteg eltűnik.
Ez a tesztek alapján nem történik meg.

**Comment by tamas-visy** [comment]
> BDD tesztelés közben felmerült a következő hibajelenség:
> Specifikáció szerint, ha egy instabil jégtábla átfordul, akkor a rajta lévő hóréteg eltűnik.
> Ez a tesztek alapján nem történik meg.

@bogarb Értettem, ez a #14-ban elméletben javításra került. A pull request után érdemes lesz leellenőrizni.
