### ISSUE TITLE
Manuális kód átvizsgálás + Statikus analízis eszközök

### ISSUE THREAD

**Issue by Mzsillye** [BME-MIT-IET/iet-hf2021-iglue#2]
# Manuális kód átvizsgálás

Manuális kód átvizsgálására a GitHub-ot, illetve valamilyen IDE-t (pl IntelliJ) használunk

# Statikus analízis eszköz

Statikus analízisre a SonarQube-ot használjuk

**Comment by Mzsillye** [comment]
Az összes említett issue le lett zárva. @tamas-visy véleményed szerint lezártnak tekinthetjük ezt az issue-t is? Ha igen, akkor kérjünk meg valakit, aki nem dolgozott a feladaton, hogy nézze meg az eredményeket, és zárjuk le.

**Comment by tamas-visy** [comment]
Én is így gondolom. Megkérem @bogarb -t hogy ellenőrizze a munkánkat, majd zárja le, ha megfelelőnek tartja.

**Comment by bogarb** [comment]
A munkátokat áttekintettem és nem találtam benne kivetnivalót, így lezárom az issue-t.
